CREATE TABLE IF NOT EXISTS daily_verses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    text TEXT NOT NULL,
    reference VARCHAR(255) NOT NULL,
    eop TEXT NULL,
    position INT DEFAULT 1,
    is_active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
